message:
  hint: "&c你还未登录，无法使用此功能！"
  success-login: "&7登陆成功！亲爱的冒险家！"
  success-register: "&7注册成功！欢迎你加入我们的服务器！"
  need-login: "&2请使用 /login <密码> 以登录！"
  need-register: "&2请使用 /reg <密码> <重复一遍密码> 以注册！"
  wrong-password: "&c密码错误！"
  wrong-old-password: "&c旧密码错误！"
  change-password: "&2密码修改成功！"
  not-same: "&c两次密码输入不符！"
  is-register: "&c你已经注册过了！"
  is-login: "&c你已经登录了！"
  never-played: "&c此玩家从未进入过游戏"
security:
  algorithm: "MD5"